name: CI

on:
  push:
    branches:
      - master
      - greenkeeper/*

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Run Lighthouse CI
        run: |
          npm install
          npm run build
          npm install -g @lhci/cli@0.3.x
          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
