name: Node.js Package

on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm run lib:ph && cp lib/oriente-ui.css ph.css
      - run: npm run lib:id && cp lib/oriente-ui.css id.css
      - run: mv ph.css id.css lib
      - run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm publish --registry=https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - run: |
          npm config set //npm.pkg.github.com/:_authToken=$GITHUB_TOKEN
          npm publish --registry=https://npm.pkg.github.com/@tpai
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
