name: Node.js Package

on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 8
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm run lib:ph && cp lib/oriente-ui.css ph.css
      - run: npm run lib:id && cp lib/oriente-ui.css id.css
      - run: mv ph.css lib
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
