name: GitHub Action for Zeit

on:
  push:
    branches:
      - master

jobs:
  publish-zeit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install
      - run: npx now --prod --token $ZEIT_TOKEN
        env:
          ZEIT_TOKEN: ${{secrets.ZEIT_TOKEN}}
