name: GitHub Action for Zeit

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 8
      - run: npm install
      - run: npm run build

  publish-zeit:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 8
      - uses: actions/zeit-now@1.0.0
        env:
          ZEIT_TOKEN: ${{secrets.ZEIT_TOKEN}}
